import type { Metadata } from "next";
import { Exo_2 } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Image from "next/image";

const exo_2 = Exo_2({
  variable: "--font-exo-2",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          exo_2.className,
          "bg-black min-h-screen text-white relative",
        )}
      >
        <div className="fixed inset-0 w-full h-full -z-10">
          <Image
            src={"/alien_bg_red.jpg"}
            alt="background"
            fill
            className="object-cover object-right"
            priority
          />
        </div>

        <div className="relative w-full min-h-screen">{children}</div>
      </body>
    </html>
  );
}
